# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fav_song',
            field=models.BooleanField(default=False),
        ),
    ]
