# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-05 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_fav_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='fav_song',
        ),
    ]
