# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170318_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_file',
            field=models.FileField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
